#!/bin/bash

# ======================================================================================================================================================== #
# curl -sSL desk2.linuxuniverse.com.br | bash
# ======================================================================================================================================================== #

datetime0=$(date '+%Y-%m-%d_%H-%M-%S')
curl -sSL https://raw.githubusercontent.com/urbancompasspony/Kubuntu/refs/heads/main/00-Base-run | tee ~/.desk-installer > /dev/null; chmod +x .desk-installer
./.desk-installer 2>&1 | tee ~/.instalacao-$datetime0.log
